### ISSUE TITLE
Why these order of commands?

### ISSUE THREAD

**Issue by fiunchinho** [joelshepherd/laravel-docker-template#1]
Just curious: why do you execute the `composer install` command with the `--no-autoloader` flag and execute `composer dump-autoload` afterwards instead of doing it together?

Thanks!

**Comment by joelshepherd** [comment]
Good question, the reason is to have Docker cache the `composer install` step, and doesn't need to rerun this step every time you rebuild after changing your app's code. It doesn't make a difference the first time you build, but it makes subsequent rebuilds much faster.

It is the `COPY` commands immediately before the composer commands that makes the difference. For the `composer install` step, it will only rerun if the `composer.json` or `composer.lock` files that are copies before it change. Whereas the `composer dump-autoload` will run any time your source code changes, as the copy command before this one copies in your entire working tree.

Checkout the "Build cache" section here for more info on Docker's build cache: https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#build-cache

**Comment by fiunchinho** [comment]
Ok, thanks!
